server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://reserva-finca-db.c12ms24q0672.us-east-2.rds.amazonaws.com/reserva_finca
    url: jdbc:postgresql://localhost:5432/fincas

    username: postgres
    password: 123456
    #password: Test123!

application:
  security:
    jwt:
      secret-key: d85193e2bdfe794b7f98a16924adf59d1e05bd7a8b157450fac917d0bf89e38b
      expiration: 86400000
